export const TRAIN_SEARCH_START = "TRAIN_SEARCH_START";
export const TRAIN_SEARCH_SUCCESS = "TRAIN_SEARCH_SUCCESS";
export const TRAIN_SEARCH_FAIL = "TRAIN_SEARCH_FAIL";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTRE_USER_FAIL = "REGISTER_USER_FAIL"
